// ranges_views.ts

import { baseSuggestion, cppStandard, isAllowed } from './types';

// Type
export interface rangesViewSuggestion extends baseSuggestion {
    standard: cppStandard;
}

// Ranges Views Dictionary
const rangeView: Record<string, rangesViewSuggestion[]> = {

    // Range Views factories
    "std::views::emp": [{ completion: "empty",   detail: "an empty view with no elements",                                                                                    standard: "C++20" }],
    "std::views::ind": [{ completion: "indices", detail: "a view that generates a sequence of increasing values from 0 up to n",                                              standard: "C++26" }],
    "std::views::iot": [{ completion: "iota",    detail: "a view consisting of a sequence generated by repeatedly incrementing an initial value",                             standard: "C++20" }],
    "std::views::ist": [{ completion: "istream", detail: "a view consisting of the elements obtained by successive application of operator>> on the associated input stream", standard: "C++20" }],
    "std::views::rep": [{ completion: "repeat",  detail: "a view consisting of a generated sequence by repeatedly producing the same value",                                  standard: "C++23" }],
    "std::views::sin": [{ completion: "single",  detail: "a view that contains a single element of a specified value",                                                        standard: "C++20" }],

    // Range Views adaptors
    "std::views::adj": [{ completion: "adjacent",           detail: "a view consisting of tuples of references to adjacent elements of the adapted view",                                                                        standard: "C++23" },
                        { completion: "adjacent_transform", detail: "a view consisting of results of application of a transformation function to adjacent elements of the adapted view",                                         standard: "C++23" }],
    "std::views::all": [{ completion: "all_t",              detail: "a view that includes all elements of a range",                                                                                                              standard: "C++20" },
                        { completion: "all",                detail: "a view that includes all elements of a range",                                                                                                              standard: "C++20" }],
    "std::views::as_": [{ completion: "as_rvalue",          detail: "a view of a sequence that casts each element to an rvalue",                                                                                                 standard: "C++23" },
                        { completion: "as_const",           detail: "converts a view into a constant_range",                                                                                                                     standard: "C++23" },
                        { completion: "as_input",           detail: "converts a view into a range that is input_range-only and non-common_range",                                                                                standard: "C++26" }],
    "std::views::cac": [{ completion: "cache_latest",       detail: "a view that caches the last-accessed element of its underlying sequence",                                                                                   standard: "C++26" }],
    "std::views::car": [{ completion: "cartesian_product",  detail: "a view consisting of tuples of results calculated by the n-ary cartesian product of the adapted views",                                                     standard: "C++23" }],
    "std::views::chu": [{ completion: "chunk",              detail: "a range of views that are N-sized non-overlapping successive chunks of the elements of another view",                                                       standard: "C++23" },
                        { completion: "chunk_by",           detail: "splits the view into subranges between each pair of adjacent elements for which the given predicate returns false",                                         standard: "C++23" }],
    "std::views::com": [{ completion: "common",             detail: "converts a view into a common_range",                                                                                                                       standard: "C++20" }],
    "std::views::con": [{ completion: "concat",             detail: "a view consisting of concatenation of the adapted views",                                                                                                   standard: "C++26" }],
    "std::views::cou": [{ completion: "counted",            detail: "creates a subrange from an iterator and a count",                                                                                                           standard: "C++20" }],
    "std::views::dro": [{ completion: "drop",               detail: "a view consisting of elements of another view, skipping the first N elements",                                                                              standard: "C++20" },
                        { completion: "drop_while",         detail: "a view consisting of the elements of another view, skipping the initial subsequence of elements until the first element where the predicate returns false", standard: "C++20" }],
    "std::views::ele": [{ completion: "elements",           detail: "takes a view consisting of tuple-like values and a number N and produces a view of Nth element of each tuple",                                              standard: "C++20" }],
    "std::views::enu": [{ completion: "enumerate",          detail: "a view that maps each element of adapted sequence to a tuple of both the element's position and its value",                                                 standard: "C++23" }],
    "std::views::fil": [{ completion: "filter",             detail: "a view that consists of the elements of a range that satisfy a predicate",                                                                                  standard: "C++20" }],
    "std::views::joi": [{ completion: "join",               detail: "a view consisting of the sequence obtained from flattening a view of ranges",                                                                               standard: "C++20" },
                        { completion: "join_with",          detail: "a view consisting of the sequence obtained from flattening a view of ranges, with the delimiter in between elements",                                       standard: "C++23" }],
    "std::views::key": [{ completion: "keys",               detail: "takes a view consisting of pair-like values and produces a view of the first elements of each pair",                                                        standard: "C++20" }],
    "std::views::laz": [{ completion: "lazy_split",         detail: "a view over the subranges obtained from splitting another view using a delimiter",                                                                          standard: "C++20" }],
    "std::views::pai": [{ completion: "pairwise",           detail: "a view consisting of pairs of references to adjacent elements of the adapted view",                                                                         standard: "C++23" },
                        { completion: "pairwise_transform", detail: "a view consisting of results of application of a transformation function to each pair of adjacent elements of the adapted view",                            standard: "C++23" }],
    "std::views::rev": [{ completion: "reverse",            detail: "a view that iterates over the elements of another bidirectional view in reverse order",                                                                     standard: "C++20" }],
    "std::views::sli": [{ completion: "slide",              detail: "a view whose Mth element is a view over the Mth through (M + N - 1)th elements of another view",                                                            standard: "C++23" }],
    "std::views::spl": [{ completion: "split",              detail: "a view over the subranges obtained from splitting another view using a delimiter",                                                                          standard: "C++20" }],
    "std::views::str": [{ completion: "stride",             detail: "a view consisting of elements of another view, advancing over N elements at a time",                                                                        standard: "C++23" }],
    "std::views::tak": [{ completion: "take",               detail: "a view consisting of the first N elements of another view",                                                                                                 standard: "C++20" },
                        { completion: "take_while",         detail: "a view consisting of the initial elements of another view, until the first element on which a predicate returns false",                                     standard: "C++20" }],
    "std::views::tra": [{ completion: "transform",          detail: "a view of a sequence that applies a transformation function to each element",                                                                               standard: "C++20" }],
    "std::views::val": [{ completion: "values",             detail: "takes a view consisting of pair-like values and produces a view of the second elements of each pair",                                                       standard: "C++20" }],
    "std::views::zip": [{ completion: "zip",                detail: "a view consisting of tuples of references to corresponding elements of the adapted views",                                                                  standard: "C++23" },
                        { completion: "zip_transform",      detail: "a view consisting of results of application of a transformation function to corresponding elements of the adapted views",                                   standard: "C++23" }],
};

// Query
export function findRangesViewSuggestions(
    wordPrefix: string,
    activeStd: cppStandard
): rangesViewSuggestion[] {

    let bestMatch: rangesViewSuggestion[] = [];

    for (let len = 3; len <= wordPrefix.length; len++) {
        const key = wordPrefix.slice(0, len);
        if (rangeView[key]) {
            bestMatch = rangeView[key].filter(s => isAllowed(s, activeStd));
        }
    }

    return bestMatch;
}